pipeline{
  tools{
    maven 'Maven'
  }
  agent any
  stages {
    stage ('Initialize'){
      steps {
        sh'''
              echo "Initializing..."
              echo "PATH = ${PATH}"
              echo "M2_HOME = ${M2_HOME}"
        '''
      }
    }

    stage ('Build'){
      steps{
        sh 'mvn - v /var/lib/jenkins/workspace/FirstGitDemo/FirstGitProj/pom.xml clean package'
      }
    }
  
  }
  
  
}
